### ISSUE TITLE
how to connect to openfire?

### ISSUE THREAD

**Issue by smartnlp** [digicoop/kaiwa#77]
fresh start and fresh openfire server,
spark can connect to openfire, but kaiwa can not, how to fix that?
any more info need I to supply?

**Comment by daltonspider** [comment]
for me same problem...

**Comment by ruofanding** [comment]
+1

**Comment by ruofanding** [comment]
I have figured out how to connect kaiwa to openfire via web socket.

Kaiwa can connect to openfire via http-bind or web socket. I first tried http-bind, but I had CORS issues caused by openfire, even though I had enabled CORS in openfire. 

Then I tried using web socket. The default certificates in openfire are considered risky by browsers, such as firefox and chrome. Therefore, when kaiwa tries to set up a web socket to the openfire server, the browser will simply disconnect the web socket. What you can do is either creating your certificate and importing it to your browser, or adding localhost:7443 as an exception in your browser.  And also in the dev_config.json, set ""wss" to "wss://localhost:7443/ws/", then the kaiwa will use web socket instead of http-bind.

**Comment by BesatZardosht** [comment]
I have the same issue with ejabberd server. This is my jabbed configuration:
```
hosts:
  - "myserver.com"
listen: 
  - 
    port: 5280
    module: ejabberd_http
    certfile: "/Applications/ejabberd-15.10/conf/myserver.pem"
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/upload": mod_http_upload
    web_admin: true
    http_bind: true
    captcha: false
```
and this is my Kaiwa config file:
```
{
   "isDev": true,
   "http": {
       "host": "localhost",
       "port": 8000
   },
   "server": {
       "domain": "myserver.com",
       "wss": "wss://myserver.com:5280/websocket/"
   }
}
```
> What you can do is either creating your certificate and importing it to your browser,

is it myserver.cert file mentioned in my ejabbed configuration file? Where should I import this certificate in Chrome?
>  or adding localhost:7443 as an exception in your browser.

Would you please explain more how to add localhost:8000 as an exception in chrome?
I tried to find these settings in Chrome but I couldn't find it.
