### ISSUE TITLE
Kaiwa can't connect on my ejabberd

### ISSUE THREAD

**Issue by Catskan** [digicoop/kaiwa#93]
Hi all,

I setting up a Kaiwa Client for use with my ejabberd server but, when I try to logging in, I have for a few second the connexion page (Connexion...) and it's redirect me on the login page. I tryed with Firefox and Chrome.

My ejabberd log's shows nothing.

kaiwa config : 

{
    "isDev": true,
    "http": {
        "host": "courstream.unice.fr",
        "port": 8000
    },
    "session": {
        "secret": "shhhhhh don't tell anyone ok?"
    },
    "server": {
        "name": "Kaiwa",
        "domain": "courstream.unice.fr",
        "wss": "wss://localhost:5281/websocket/",
        "muc": "conference.courstream.unice.fr",
        "startup": "groupchat/room%40conference.courstream.unice.fr",
        "admin": "admin"
    }
}

ejabberd running on the same server as kaiwa.

Thanks you in advance for your help.

**Comment by wolkenschieber** [comment]
Hi,

I got Kawai running with ejabberd.

1. Make sure, you have *websockets* enabeled in your *ejabberd.yml*

```
    port: 5284
    module: ejabberd_http
    certfile: "/etc/ejabberd/ejabberd.pem"
    tls: true
    web_admin: true
    http_poll: true
    http_bind: true
    request_handlers:
       "/websocket": ejabberd_http_ws
```

2. Configure Kawai through *dev_config.json*

```
{
    "isDev": true,
    "http": {
        "host": "yourpublicIP",
        "port": 8000
    },
    "session": {
        "secret": "someverysecretsecrets"
    },
    "server": {
        "domain": "yourdomain.com",
        "wss": "wss://yourdomain.com:5284/websocket"
    }
}
```

Above configuration should set up server and Kawai client. Try to login through Firefox. This browser is unreliable, login often fails, but with Chrome I had no success at all.

Cheers
